{
 "title": "PocketMine-MP Dashboard",
 "time": { "from": "2020-05-30T18:39:36.677Z", "to": "2020-05-30T18:55:48.235Z" },
 "panels": [
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "pmmp_ticks_per_second" }
   ]
  },
  {
   "title": "Tick Usage (Current)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "pmmp_tick_usage" }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pmmp_ticks_per_second", "legendFormat": "TPS ({{instance}})" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "pmmp_memory_heap_bytes", "legendFormat": "Heap ({{instance}})" },
    { "expr": "pmmp_memory_main_thread_bytes", "legendFormat": "Main Thread ({{instance}})" },
    { "expr": "pmmp_memory_total_bytes", "legendFormat": "Total ({{instance}})" }
   ]
  },
  {
   "title": "Tick Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "pmmp_tick_usage", "legendFormat": "Tick Usage ({{instance}})" }
   ]
  },
  {
   "title": "Network Upload/Download",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "expr": "pmmp_network_upload_bytes", "legendFormat": "Upload ({{instance}})" },
    { "expr": "pmmp_network_download_bytes", "legendFormat": "Download ({{instance}})" }
   ]
  },
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "pmmp_player_online_count" }
   ]
  },
  {
   "title": "Total Players (statistics)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pmmp_player_total_count", "legendFormat": "Total Player ({{instance}})" }
   ]
  },
  {
   "title": "Worlds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(pmmp_world_loaded)" }
   ]
  },
  {
   "title": "Loaded Chunk Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pmmp_world_chunk_loaded",
     "legendFormat": "{{world}} ({{instance}}/{{world_folder}})"
    }
   ]
  },
  {
   "title": "World Tick Rate Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pmmp_world_tick_rate",
     "legendFormat": "{{world}} ({{instance}}/{{world_folder}})"
    }
   ]
  },
  {
   "title": "Online Players",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pmmp_player_online_count", "legendFormat": "Online ({{instance}})" }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pmmp_thread_count", "legendFormat": "Thread Count ({{instance}})" }
   ]
  },
  {
   "title": "Worlds",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "pmmp_world_chunk_loaded-0" },
    { "expr": "pmmp_world_entity_count-0" },
    { "expr": "pmmp_world_tick_rate" },
    { "expr": "pmmp_world_disk_usage_bytes-0" },
    { "expr": "pmmp_world_player_count-0" }
   ]
  },
  {
   "title": "Players in World",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pmmp_world_player_count",
     "legendFormat": "{{world}} ({{instance}}/{{world_folder}})"
    }
   ]
  },
  {
   "title": "World Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pmmp_world_disk_usage_bytes",
     "legendFormat": "{{world}} ({{instance}}/{{world_folder}})"
    }
   ]
  },
  {
   "title": "Entities in World",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pmmp_world_entity_count",
     "legendFormat": "{{world}} ({{instance}}/{{world_folder}})"
    }
   ]
  }
 ]
}